### ISSUE TITLE
Add more LeCroy trigger sources

### ISSUE THREAD

**Issue by antikerneldev** [azonenberg/scopehal#100]
Currently does not support trigger source Line "ERROR: Unknown source LINE"

Trigger Sources shown on the DDA-5005A are: C1,C2,C3,C4,Ext*10,Ext, Ext/10,Line and grayed out "Pattern"

**Comment by azonenberg** [comment]
Closing as redundant, we now have separate tickets for each type of trigger that aren't yet supported
