### ISSUE TITLE
Remove support for non-queued acquisition mode in Oscilloscope::AcquireData()

### ISSUE THREAD

**Issue by azonenberg** [azonenberg/scopehal#132]
The current toQueue=true as default model seems to confuse people.

Maybe it makes more sense to define AcquireData() as only writing to the FIFO, then require a separate pop operation to read the data?

This isn't a final decision, looking for comments.

**Comment by noopwafel** [comment]
this would also simplify driver code, since it no longer has to special-case the first segment as "the one which might not go in the FIFO", so +1

**Comment by azonenberg** [comment]
Decision made, we're doing it. Might be a while before I get to it though.
