### ISSUE TITLE
Add Agilent/Keysight scope driver(s)

### ISSUE THREAD

**Issue by azonenberg** [azonenberg/scopehal#14]

**Comment by miek** [comment]
Initial support got merged in #91. Some TODOs still for a reasonable level of support:

- [ ] Digital channels
- [ ] SetChannelAttenuation
- [ ] SetChannelVoltageRange
- [ ] SetChannelOffset
- [ ] SetTriggerChannelIndex
- [ ] Get/SetTriggerType
- [ ] Sample rates/depths

**Comment by azonenberg** [comment]
We should figure out how to add an alias so that the same driver is used for Keysight scopes too. Might also want to rename the class to KeysightOscilloscope as that's the current name, with "agilent" as an alias for older hardware?
