### ISSUE TITLE
Add Picoscope scope driver(s)

### ISSUE THREAD

**Issue by azonenberg** [azonenberg/scopehal#15]

**Comment by bvernoux** [comment]
Does it is too early to start working on adding Picoscope ?
* After checking quickly the code it seems a good start will be to use class example like LeCroyOscilloscope.cpp/.h
* Does the Interface/Class with members... is frozen ? (maybe it is too early to work on Picosope driver ?)

**Comment by noopwafel** [comment]
As discussed on IRC: I started hacking up a prototype SCPI bridge for my 3000-series Picoscope, with data going over a separate socket as in AntikernelLabsOscilloscope.

**Comment by bvernoux** [comment]
@noopwafel Do you have any news about your prototype SCPI bridge for my 3000-series Picoscope ?
I have a PicoScope 3406DMSO so I'm very interested by this driver as it shall be very fast in theory over USB 3.0

**Comment by noopwafel** [comment]
I got (very very) swamped by work, but getting back to this is now nearer the top of my todo (likely next week?). Feel free to ping me about it. I don't have (access to) an MSO, so would be nice to hack that in too.

**Comment by bvernoux** [comment]
Yes everyone is very busy with tons of things to do and we do that on our spare time so there is no hurry
I'm very interested if you have something usable to test to help and even improve it for PicoScope 3000-series (especially I have the full version) and I could test also on Windows.

**Comment by sbabic44** [comment]
I also have a PicoScope 3406DMSO and be willing to test...

**Comment by azonenberg** [comment]
@sbabic44 Unfortunately Pico's driver model uses a separate SDK for each one of their families. In order to clean this up a bit and provide network transparency (a key feature for me since my main desk is about 20 meters from the lab bench), I'm using a bridge server (https://github.com/azonenberg/scopehal-pico-bridge) as the point of abstraction which currently only supports the 6000 series.

Once I've finished 6000 series support I'm definitely interested in supporting lower end models. Some refactoring will be needed though, as right now the ps6000d application contains a bunch of SCPI parsing code etc that should probably be shared across the different server binaries.

**Comment by azonenberg** [comment]
Closed this ticket as 6000 series support is at "minimum viable" level.

Feel free to file additional tickets for specific features. Requests for new instrument support should be filed against scopehal-pico-bridge instead, as the network protocol used by the PicoOscilloscope class is intended to be the same for all instruments.
