### ISSUE TITLE
Windows portability fixes

### ISSUE THREAD

**Issue by azonenberg** [azonenberg/scopehal#153]
This is an umbrella issue for "make scopehal compile and work under Windows".

**Comment by azonenberg** [comment]
@nshcat Please close this issue once you believe the Windows build has reached feature parity with the Linux build.

**Comment by nshcat** [comment]
libscopehal builds in windows, and has feature-parity with the linux build. Any bugs or differences in behaviour between the different platforms will be tracked in separate issues.
