### ISSUE TITLE
Channel names not populating in "Trigger properties" dialogue (Rigol DS1054Z)

### ISSUE THREAD

**Issue by Cushychicken** [azonenberg/scopehal#331]
The "din" menu is popping up empty for me. Running Ubuntu 20.04, connected over USBTMC to a Rigol DS1054Z.

Looks like the "din" channel name list has the right number of entries (one blank for no channel selected, and four more - one for each analog scope channel), but no names associated with them. 

![Screenshot from 2020-10-31 08-24-47](https://user-images.githubusercontent.com/3886137/97779152-adad0e00-1b52-11eb-8242-eb33d2032fc9.png)

Perhaps `GetDisplayName()` is turning up blank for Rigol scopes? (Happy to check this behind the scenes if there's means of accessing that via CLI) 

https://github.com/azonenberg/scopehal-apps/blob/3752d10fc8a21ea60da8b81ed4c2f7ed17b7e665/src/glscopeclient/TriggerPropertiesDialog.cpp#L208

**Comment by azonenberg** [comment]
Can you provide a screenshot of the main glscopeclient window without trigger properties open?

**Comment by Cushychicken** [comment]
Howzat? 

![Screenshot from 2020-10-31 08-36-19](https://user-images.githubusercontent.com/3886137/97779412-32e4f280-1b54-11eb-972b-7f2a3f54dd93.png)

**Comment by azonenberg** [comment]
There's supposed to be channel label buttons in the bottom left of each channel, as in this screenshot.

What's interesting is that I'm not seeing sample rate information either. If you double-click that tiny blob do you get a channel properties dialog? And if you enter a name for the channel does it act somewhat more sane?

![100basetx-eyemask](https://user-images.githubusercontent.com/998036/97779445-5780a080-1b3b-11eb-978f-
8ef0e6ded34d.png)

**Comment by Cushychicken** [comment]
Yep - I just see blank entries for all of those by default. 

I _am_ able to click those label buttons and edit the channel name: 

![Screenshot from 2020-10-31 08-41-28](https://user-images.githubusercontent.com/3886137/97779533-054c7900-1b55-11eb-9a52-44ad75be57d1.png)

And that channel name, in turn, appears to propagate to the trigger properties:

![Screenshot from 2020-10-31 08-43-04](https://user-images.githubusercontent.com/3886137/97779546-1d23fd00-1b55-11eb-9512-4b6f8e166884.png)

(Also please tell me you're in Europe or somewhere - I'd hate to think I woke you up at quarter to 6 PST to talk trigger properties)

**Comment by azonenberg** [comment]
I'm in the Seattle area, but my sleep schedule is destroyed from not having to wake up at a consistent time to go into the office for the past 6+ months :P I've actually been up since around 4AM Pacific time.

So what this tells me is that the glscopeclient UI is correctly handling an empty channel name, and the Rigol driver is incorrectly supplying an empty name by default. When you open the channel properties dialog, under "scope" and "channel" do you see plausible values, or is the "channel" line above "display name" blank?

**Comment by Cushychicken** [comment]
`scope` and `channel` both appear like plausible values:

![Screenshot from 2020-10-31 08-56-30](https://user-images.githubusercontent.com/3886137/97779816-0e3e4a00-1b57-11eb-8a81-d72dccc561f0.png)

I'm guessing you'd expect something like `CHAN1` to be the default channel name, and also show up in the Trigger properties dialogue? 

> I'm in the Seattle area, but my sleep schedule is destroyed from not having to wake up at a consistent time to go into the office for the past 6+ months :P I've actually been up since around 4AM Pacific time.

That eases my mind a bit - I don't want to feel like I'm dragging you out of bed at godawful o'clock for this! You're certainly not alone on the sleeplessness front. I can't remember the last time I slept past 6 AM. How on earth is not having a regular job schedule making me wake up _earlier?!_

**Comment by azonenberg** [comment]
Very interesting, so the hardware channel name is correct. The display name *should* default to the hardware channel name. I'm gonna have to do some digging here.

**Comment by Cushychicken** [comment]
Anything I can do to help? 

As an aside - I read thru the manual and saw some references to Siglent's scopes being based off of Teledyne Lecroy firmware. Would you expect Siglent's scopes to have better functionality with glscopeclient?

(I'd love to pick your brain about this via email - got some questions I don't want to spam GitHub comments with - email me? You can reach me at <my GitHub handle> @ gmail.com)

**Comment by azonenberg** [comment]
IRC is best, join #scopehal on Freenode? I have to run and take care of somethign but will be back at my desk in half an hour or so.

**Comment by Cushychicken** [comment]
Never tried Freenode but there's a first time for everything - see you on there :+1:

**Comment by azonenberg** [comment]
1af3ff87851660775578abf347a1680ecbda9105 should fix it, please test and close this issue if you can confirm the fix.

**Comment by Cushychicken** [comment]
Fix confirmed! See screenshot below. Closing.  

![Screenshot from 2020-10-31 14-03-43](https://user-images.githubusercontent.com/3886137/97786454-1364be80-1b82-11eb-9634-33eb8b123bc2.png)
