### ISSUE TITLE
Add Agilent MSO6104A support via SCPI

### ISSUE THREAD

**Issue by clh27** [azonenberg/scopehal#74]

**Comment by miek** [comment]
I've got the beginnings of a driver working for the DSO5014A here: https://github.com/miek/scopehal/tree/agilent
It will probably just work on the 6000 & 7000 series if you want to try it out.

**Comment by miek** [comment]
Duplicate of #14 - the MSO6104A should work just fine with the Agilent driver I'm developing on an MSO6034A
